### ISSUE TITLE
Doesn't work in OSX Elcapitan

### ISSUE THREAD

**Issue by cksachdev** [nicolas-goudry/subl-autoconf#1]
```
curl -L "https://bitbucket.org/ngoudry/st3-conf/raw/default/install.sh" | bash -s 3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1179  100  1179    0     0    880      0  0:00:01  0:00:01 --:--:--   881
requesting all changes
adding changesets
adding manifests
adding file changes
added 42 changesets with 285 changes to 221 files
updating to branch default
207 files updated, 0 files merged, 0 files removed, 0 files unresolved
*** Install complete :)
```

I tried to run it in a directory and it says, Install complete but no package is installed. Do I need to run it in a specific directory?

**Comment by nicolas-goudry** [comment]
Actually, the script for Linux/Mac is outdated :confused: Didn't take time to update them yet, so they match the [original fork](https://bitbucket.org/efolio/sublime-text-3-config).

Can you tell me if the directory (under your home directory) `Library/Application Support/Sublime Text` exists ? If it exists, look into the `Packages` folder to see if some packages are installed.

You can also try to use the original fork, but there isn't as much tooling as in mine and no `standardJS`.

**Comment by nicolas-goudry** [comment]
Closing.

See #2.
